config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
  }
  resources :categories, only: [:index, :show]
  resources :middle_categories, only: [:index, :show]
  resources :lower_categories, only: [:index, :show]
  resources :brands, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items do
    get :search, on: :collection
    resources :likes, only: [:create]
    resources :comments, only: [:create]
    resources :orders, only:[:new, :create]
  end
  root 'items#index'
  get 'users/new'
  post 'users/create'
  get 'top', to: 'items#top'
  get 'mypage', to: 'users#mypage'
  get 'profile', to: 'users#profile'
  get 'userconfirm', to: 'users#userconfirm'
  get 'userlogout', to: 'users#userlogout'
  get 'credit', to: 'users#credit'
  get 'creditregistration', to: 'users#creditregistration'
  get 'itemconfirm', to: 'users#itemconfirm'
  get 'sign_up', to: 'users#sign_up'
  get 'itemsell', to: 'users#itemsell'

  resources :credit_card, only:[:index, :new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable
  has_many :social_profiles, dependent: :destroy
  has_one :credit, dependent: :destroy
  has_many :items
  has_many :likes
  has_many :like_items, through: :likes, source: :item
  has_many :comments
  has_many :orders
  validates :nickname, presence: true,length: { maximum: 20 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :year, presence: true
  validates :month, presence: true
  validates :day, presence: true

  def social_profile(provider)
    social_profiles.select{ |sp| sp.provider == provider.to_s }.first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
    @profile = SocialProfile.where(provider: session[:provider], uid: session[:uid]).new
    @profile.user = current_user || User.create(sns_sign_up)
    @profile.save!
    redirect_to new_user_session_path

  end

  def top
  end

  def mypage
  end

  def profile
  end

  def userconfirm
  end

  def userlogout
  end

  def credit
  end

  def creditregistration
  end

  def itemsell
  end


  def itemconfirm
  end

  def sign_up
  end

  private

  def sns_sign_up
    params.permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:birthday).merge(nickname: session[:nickname],email: session[:email], password: session[:password])
  end



end

app/views/users/_bread-crumbs.html.haml
%nav.bread-crumbs
  %ul
    %li
      = breadcrumbs pretext: "", separator: " #{content_tag(:i, '', :class=>'fa fa-angle-right' )} "

app/views/users/_footer.haml
.top-app-baner.clearfix
  .top-app-baner__content
    .top-app-baner__content__inner
      %h2.bold.top-app-baner__content__inner__introduction スマホでかんたんフリマアプリ
      %p.top-app-baner__content__inner__introduction 今すぐ無料ダウンロード！
      %ul
        %li
          %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?206587138", width: "68"}/
        %li
          %a{href:"https://itunes.top-apple.com/jp/top-app/id667861049?l=ja&amp;mt=8",target:"_blank"}
          %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?206587138", width: "133",height:"40"}
        %li
          %a{href:"https://play.google.com/store/top-apps/details?id=com.kouzoh.mercari&hl=ja",target: "_blank"}
          %img{alt: "", height: "40",src: "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?206587138", width:"133"}/
    .top-app-baner__content__iPhone
      %img{alt: "",src: "//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?206587138",id:"sp",height: "260px"}/
.footer__under
  .footer__under__map
    %ul
      %li
        %h4 メルカリについて
        %ul.footer__under__map--list
          %li
            =link_to "会社概要(運営会社)" , root_path
          %li
            =link_to "プライバシーポリシー" , root_path
          %li
            =link_to "メルカリ利用規約" , root_path
          %li
            =link_to "有償ポイントに関する特約" , root_path
          %li
            =link_to "あんしんスマホサポート制度に関する利用特約" , root_path
          %li
            =link_to "コンプライアンスポリシー" , root_path
          %li
            =link_to "個人データの安全管理に係る基本方針" , root_path
          %li
            =link_to "特定商取引に関する表記" , root_path
          %li
            =link_to "資金決済法に基づく表記" , root_path
          %li
            =link_to "法令遵守と犯罪抑止のために" , root_path
          %li
            =link_to "採用情報" , root_path
      %li
        %h4.bold メルカリをみる
        %ul.footer__under__map--list
          %li
            =link_to "カテゴリー一覧" , root_path
          %li
            =link_to "ブランド一覧" , root_path
          %li
            =link_to "出品地域一覧" , root_path
          %li
            =link_to "公式ブログ" , root_path
          %li
            =link_to "公式Twitter" , root_path
          %li
            =link_to "公式Facebook" , root_path
      %li
        %h4.bold ヘルプ＆ガイド
        %ul.footer__under__map--list
          %li
            =link_to "メルカリガイド" , root_path
          %li
            =link_to "メルカリロゴ利用ガイドライン" , root_path
          %li
            =link_to "お知らせ" , root_path
          %li
            =link_to "らくらくメルカリ便とは" , root_path
          %li
            =link_to "ゆうゆうメルカリ便とは" , root_path
          %li
            =link_to "大型らくらくメルカリ便とは" , root_path
          %li
            =link_to "車体取引ガイド" , root_path
          %li
            =link_to "返品・返金ポリシー" , root_path
          %li
            =link_to "メルカリあんしん・あんぜん宣言！" , root_path
          %li
            =link_to "偽ブランド品撲滅への取り組み" , root_path
          %li
            =link_to "メルカリボックス" , root_path
      %li
        %h4.bold 国
        %ul.footer__under__map--list
          %li.opacity
            =link_to "United States" , root_path
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?3703848211", :width => "22"}
          %li.opacity
            =link_to "United Kingdom" , root_path
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?3703848211", :width => "22"}
          %li.auto
            =link_to "日本" , root_path
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?3703848211", :width => "22"}

  .footer__under__copyright
    %a.footer__under__copyright--logo{href: "https://www.mercari.com/jp/"}
      %img{alt: "mercari", height: "33", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?206587138", width: "124"}/
    %p.footer__under__copyright--text
      %small © 2019 Mercari

app/views/users/_header.html.haml
%header.top-header
  .top-header__inner
    .top-header__inner__top
      %h1.top-header__inner__top__logo
        = link_to image_tag('mercari_logo.svg', alt: 'mercari', width: '134', height: '36'), root_path
      %form.top-header-form{:action => "https://www.mercari.com/jp/search/"}
        %input.top-header-form__input{:name => "keyword", :placeholder => "キーワードから探す", :type => "search", :value => ""}
        %i.top-icon-search
          = fa_icon("search")

    .top-nav.clearfix
      %nav.top-nav__left
        %ul.top-nav__left__nav
          %li.top-nav__left__nav__list
            %h2.top-nav__left__nav__list__select
              %a.top-nav__left__nav__list__select__root{:href => "https://www.mercari.com/jp/category/"} カテゴリーから探す
          %li.top-nav__left__nav__list2
            %h2.top-nav__left__nav__list2__select
              %a.top-nav__left__nav__list2__select__root{:href => "https://www.mercari.com/jp/brand/"} ブランドから探す

      %nav.top-right
        %ul.top-right__nav
          %li.top-right__nav__list1
            = link_to '/testpage' do
              = image_tag("sample.jpg",class: "top-right__nav__list1__icon",width: '32',height: '32')
              .top-mypage マイページ

          %li.top-right__nav__list2
            = link_to '/testpage' do
              %i.top-right__nav__list2__bell
                = fa_icon("bell")
              %span.top-bell お知らせ

          %li.top-right__nav__list3
            = link_to '/testpage' do
              %i.top-right__nav__list3__check
                = fa_icon("check")
                %span.top-check やることリスト
            %li
              = link_to "ログイン", new_user_session_path, class: "login-link"
            %li
              = link_to "新規会員登録", new_user_registration_path, class: "registration-link"

app/views/users/_top-footer.html.haml
.top-app-baner.clearfix
  .top-app-baner__content
    .top-app-baner__content__inner
      %h2.bold.top-app-baner__content__inner__introduction スマホでかんたんフリマアプリ
      %p.top-app-baner__content__inner__introduction 今すぐ無料ダウンロード！
      %ul
        %li
          %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?206587138", width: "68"}/
        %li
          %a{href:"https://itunes.top-apple.com/jp/top-app/id667861049?l=ja&amp;mt=8",target:"_blank"}
          %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?206587138", width: "133",height:"40"}
        %li
          %a{href:"https://play.google.com/store/top-apps/details?id=com.kouzoh.mercari&hl=ja",target: "_blank"}
          %img{alt: "", height: "40",src: "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?206587138", width:"133"}/
    .top-app-baner__content__iPhone
      %img{alt: "",src: "//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?206587138",id:"sp",height: "260px"}/
.footer__under
  .footer__under__map
    %ul
      %li
        %h4 メルカリについて
        %ul.footer__under__map--list
          %li
            =link_to "会社概要(運営会社)" , root_path
          %li
            =link_to "プライバシーポリシー" , root_path
          %li
            =link_to "メルカリ利用規約" , root_path
          %li
            =link_to "有償ポイントに関する特約" , root_path
          %li
            =link_to "あんしんスマホサポート制度に関する利用特約" , root_path
          %li
            =link_to "コンプライアンスポリシー" , root_path
          %li
            =link_to "個人データの安全管理に係る基本方針" , root_path
          %li
            =link_to "特定商取引に関する表記" , root_path
          %li
            =link_to "資金決済法に基づく表記" , root_path
          %li
            =link_to "法令遵守と犯罪抑止のために" , root_path
          %li
            =link_to "採用情報" , root_path
      %li
        %h4.bold メルカリをみる
        %ul.footer__under__map--list
          %li
            =link_to "カテゴリー一覧" , root_path
          %li
            =link_to "ブランド一覧" , root_path
          %li
            =link_to "出品地域一覧" , root_path
          %li
            =link_to "公式ブログ" , root_path
          %li
            =link_to "公式Twitter" , root_path
          %li
            =link_to "公式Facebook" , root_path
      %li
        %h4.bold ヘルプ＆ガイド
        %ul.footer__under__map--list
          %li
            =link_to "メルカリガイド" , root_path
          %li
            =link_to "メルカリロゴ利用ガイドライン" , root_path
          %li
            =link_to "お知らせ" , root_path
          %li
            =link_to "らくらくメルカリ便とは" , root_path
          %li
            =link_to "ゆうゆうメルカリ便とは" , root_path
          %li
            =link_to "大型らくらくメルカリ便とは" , root_path
          %li
            =link_to "車体取引ガイド" , root_path
          %li
            =link_to "返品・返金ポリシー" , root_path
          %li
            =link_to "メルカリあんしん・あんぜん宣言！" , root_path
          %li
            =link_to "偽ブランド品撲滅への取り組み" , root_path
          %li
            =link_to "メルカリボックス" , root_path
      %li
        %h4.bold 国
        %ul.footer__under__map--list
          %li.opacity
            =link_to "United States" , root_path
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?3703848211", :width => "22"}
          %li.opacity
            =link_to "United Kingdom" , root_path
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?3703848211", :width => "22"}
          %li.auto
            =link_to "日本" , root_path
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?3703848211", :width => "22"}

  .footer__under__copyright
    %a.footer__under__copyright--logo{href: "https://www.mercari.com/jp/"}
      %img{alt: "mercari", height: "33", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?206587138", width: "124"}/
    %p.footer__under__copyright--text
      %small © 2019 Mercari

app/views/users/_top-header.html.haml
%header.top-main-header
  .top-main-header__wrapper
    .top-main-header__wrapper__top
      .top-main-header__wrapper__top__left
        %a{:href => root_path}
          = image_tag("mercari_logo.svg", class: "mercari-image")
      = form_with url: search_items_path, method: :get, local: true ,html: {class: "top-main-header__wrapper__top__form"} do |f|
        .top-main-header__wrapper__top__form__search-field.back-silver
          = f.text_field :keyword, class: 'top-main-header__wrapper__top__form__search-field__text-field', placeholder: 'キーワードから探す'
          = button_tag type: 'submit', class: 'top-main-header__wrapper__top__form__search-field__search-btn' do
            %i.fa.fa-search
    .top-main-header__wrapper__nav-box
      .top-main-header__wrapper__nav-box__left
        %ul.category
          %i.fa.fa-list
          %li.category__list
            = link_to "カテゴリーから探す",root_path,class:"category__list__text"
            %ul.top-main-header-nav-parent-wrap
              - @categories.each do |category|
                %li.top-main-header-nav-parent{"data-category-id": category.id}
                  %h3.category__text
                    = link_to category_path(category), class: "category_link" do
                      = category.name
                  %ul.top-main-header-nav-child-wrap
                    - if category.middle_categories.present?
                      - category.middle_categories.each do |middle_category|
                        %li.top-main-header-nav-child{"data-middle-id": middle_category.id}
                          = link_to middle_category_path(middle_category), class: "middle_category_link" do
                            = middle_category.name
                          %ul.top-main-header-nav-grand-child-wrap
                            - if middle_category.lower_categories.present?
                              - middle_category.lower_categories.each do |lower_category|
                                %li.top-main-header-nav-grand-child{"data-lower-id": lower_category.id}
                                  = link_to lower_category_path(lower_category), class: "lower_category_link" do
                                    = lower_category.name
                            - else
                              %li.top-main-header-nav-grand-child
                    - else
                      %li.top-main-header-nav-child
          %i.fa.fa-tag
          %li.brand__list
            = link_to "ブランドから探す",root_path,class:"brand__list__text"
            %ul.top-main-header-nav-brand-wrap
              - @brands.each do |brand|
                %li.top-main-header-nav-brand{"data-brand-id": brand.id}
                  %h3.brand__text
                    = link_to brand_path(brand), class: "brand_link" do
                      = brand.name
      .top-main-header__wrapper__nav-box__right
        %ul.right
          - if user_signed_in?

            %li
              = link_to mypage_path(current_user.id) do
                = image_tag("sample.jpg", class: "avater-image")
                %span マイページ
              %ul.mypage-box
                .profile-area
                  .profile-area__avatar
                    = image_tag("sample.jpg")
            %li.bell-color
              = link_to root_path do
                %i.fa.fa-bell
                %span お知らせ
            %li
              = link_to root_path do
                %i.fa.fa.fa-check
                %span やることリスト
          - else
            %li
              = link_to "ログイン", new_user_session_path, class: "login-link"
            %li
              = link_to "新規会員登録", new_user_registration_path, class: "registration-link"

app/views/users/_top.html.haml
%header.top-header
  .top-header__inner
    .top-header__inner__top
      %h1.top-header__inner__top__logo
        = link_to image_tag('mercari_logo.svg', alt: 'mercari', width: '134', height: '36'), root_path
      %form.top-header-form{:action => "https://www.mercari.com/jp/search/"}
        %input.top-header-form__input{:name => "keyword", :placeholder => "キーワードから探す", :type => "search", :value => ""}
        %i.top-icon-search
          = fa_icon("search")

    .top-nav.clearfix
      %nav.top-nav__left
        %ul.top-nav__left__nav
          %li.top-nav__left__nav__list
            %h2.top-nav__left__nav__list__select
              %a.top-nav__left__nav__list__select__root{:href => "https://www.mercari.com/jp/category/"} カテゴリーから探す
          %li.top-nav__left__nav__list2
            %h2.top-nav__left__nav__list2__select
              %a.top-nav__left__nav__list2__select__root{:href => "https://www.mercari.com/jp/brand/"} ブランドから探す

      %nav.top-right
        %ul.top-right__nav
          %li.top-right__nav__list1
            = link_to '/testpage' do
              = image_tag("sample.jpg",class: "top-right__nav__list1__icon",width: '32',height: '32')
              .top-mypage マイページ

          %li.top-right__nav__list2
            = link_to '/testpage' do
              %i.top-right__nav__list2__bell
                = fa_icon("bell")
              %span.top-bell お知らせ

          %li.top-right__nav__list3
            = link_to '/testpage' do
              %i.top-right__nav__list3__check
                = fa_icon("check")
                %span.top-check やることリスト
            %li
              = link_to "ログイン", new_user_session_path, class: "login-link"
            %li
              = link_to "新規会員登録", new_user_registration_path, class: "registration-link"

app/views/users/credit.html.haml
= render 'users/top-header'
.um-default
  - breadcrumb :credit
  = render 'users/bread-crumbs'
  .um-container
    = render 'devise/shared/side_bar'
    .uc-content
      %section.uc-content__chapter
        %h2.uc-content__chapter__head 支払い方法
        .uc-single
          %section.uc-single__inner
            .uc-single__content
              %h3.uc-content-chapter-sub-head クレジットカード一覧
            %ul.uc-payment-list
          %section.uc-add-card
            .uc-single__content
              - if @card_info
                -# [@ToDo]ビューの調整必要
                %p.ib-content__payment-inner__info
                  = "************#{@card_info[:last4]}"
                  %br
                  = "#{@card_info[:exp_month]} / #{@card_info[:exp_year]}"
                .ib-content__payment-inner__visa
                  = get_credit_log(@card_info[:brand])
                -# [@ToDo]Myページから遷移時のみ削除ボタンを表示させるようにする
                =link_to "/credit_card/:id", method: :delete, class: 'um-mypage-nav-list-item' do
                  削除する
              - else
                = link_to creditregistration_path, data:{turbolinks: "false"}, class: "uc-btn-default uc-btn-red submit_btn" do
                  クレジットカードを追加する
                  = fa_icon 'credit-card', class: 'icon'
          .uc-settings
            = link_to "#" do
              支払い方法について
              = fa_icon 'angle-right', class: 'icon'
= render 'users/camera-btn'
= render 'users/top-footer'

app/views/users/creditregistration.html.haml
= render 'users/top-header'
.um-default
  - breadcrumb :creditregistration
  = render 'users/bread-crumbs'
  .um-container
    .credit-right-content
      .credit-right-content__wrapper
        %h2.credit-title クレジットカード情報入力
      .credit-right-content__wrapper__box
        -# [@kari]↓仮のルーティング設定。user_idと紐付け必要
        = form_with url: "/credit_card" ,local: true, id:"credit_form", class: "credit-right-content__wrapper__box__form" do |f|
          .credit-right-content__wrapper__box__form__center
            .credit-right-content__wrapper__box__form__center__number
              .h4.number-title カード番号
              %span.form-require 必須
            = f.text_field :credit_card_number, class: 'number-form', placeholder: '半角数字のみ'

            %ul.card-all
              %li
                = get_credit_log('visa')
              %li
                = get_credit_log('mastercard')
              %li
                = get_credit_log('saison')
              %li
                = get_credit_log('jcb')
              %li
                = get_credit_log('american express')
              %li
                = get_credit_log('diners club')
              %li
                = get_credit_log('discover')
            .credit-right-content__wrapper__box__form__center__expiration-month
              .h4.expiration-title 有効期限
              %span.form-require 必須
            %select.form-month#credit_month
              %option{value: "1"} 01
              %option{value: "2"} 02
              %option{value: "3"} 03
              %option{value: "4"} 04
              %option{value: "5"} 05
              %option{value: "6"} 06
              %option{value: "7"} 07
              %option{value: "8"} 08
              %option{value: "9"} 09
              %option{value: "10"} 10
              %option{value: "11"} 11
              %option{value: "12"} 12
            %span 月

            .credit-right-content__wrapper__box__form__center__expiration-year
            %select.form-month#credit_year
              %option{value: "19"} 19
              %option{value: "20"} 20
              %option{value: "21"} 21
              %option{value: "22"} 22
              %option{value: "23"} 23
              %option{value: "24"} 24
              %option{value: "25"} 25
              %option{value: "26"} 26
              %option{value: "27"} 27
              %option{value: "28"} 28
              %option{value: "29"} 29
            %span 年
            .credit-right-content__wrapper__box__form__security
              .credit-right-content__wrapper__box__form__center__number
                .h4.number-title セキュリティコード
                %span.form-require 必須
              = f.text_field :credit_card_security_code, class: 'number-form', placeholder: 'カード背面4桁もしくは3桁の番号'
            .credit-right-content__wrapper__box__form__caution
              %span.question ?
              .credit-question-number カード裏面の番号とは？
            = f.hidden_field :card_token
            %button.submit-button#submit-button 追加する

    =render 'devise/shared/side_bar'
= render 'users/camera-btn'
= render 'users/top-footer'

app/views/users/index.html.haml
%p test

app/views/users/mypage.html.haml
= render 'users/top-header'
.um-default
  - breadcrumb :mypage
  = render 'users/bread-crumbs'
  .um-container
    = render 'devise/shared/side_bar'
    = render 'devise/shared/um-content'
= render 'users/camera-btn'
= render 'users/top-footer'

app/views/users/new.html.haml
.ur-content
  %header.ur-header
    %h1.ur-header__icon
      = link_to root_path ,class: "ur-header__icon--link" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2405105395" ,alt: "mercari",class: "ur-header__icon--link-img"
    %nav.ur-hd-nav
      %ol.ur-hd-nav__ol
        %li.ur-hd-nav__list.ur-hd-nav__list--active 会員情報
        %li.ur-hd-nav__list 電話番号認証
        %li.ur-hd-nav__list お届け先住所入力
        %li.ur-hd-nav__list 支払い方法
        %li.ur-hd-nav__list 完了
  %main.ur-main
    %section.ur-section
      %h2.ur-m-header 会員情報入力
      .ur-form
        .ur-form-content
          = form_with url: users_create_path do |f|
            .ur-form-group
              = f.label :ニックネーム , class: "ur-form-group__label"
              %span.ur-form-group__span 必須
              = f.text_field :nickname, autofocus: true, autocomplete: "nickname" ,value: session[:nickname], placeholder:"例) メルカリ太郎", class: "ur-form-group__field"
            .ur-form-group
              = f.label :メールアドレス , class: "ur-form-group__label"
              %span.ur-form-group__span 必須
              = f.email_field :email, autofocus: true, autocomplete: "email" ,value: session[:email], placeholder:"PC・携帯どちらでも可", class: "ur-form-group__field"
              = f.hidden_field :password, autocomplete: "new-password",placeholder:"6文字以上",value: session[:password],class: "ur-form-group__field"
              = f.hidden_field :password_confirmation, autocomplete: "new-password",placeholder:"6文字以上",value: session[:passwoed],class: "ur-form-group__field"
            .ur-form-group
              %h3.ur-form-group__confirm 本人確認
              %p.ur-form-group__text 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .ur-form-group
              = f.label :"姓 (全角)" , class: "ur-form-group__label"
              %span.ur-form-group__span 必須
              = f.text_field :last_name, autofocus: true, autocomplete: "last_name" ,placeholder:"例) 山田", class: "ur-form-group__field"
            .ur-form-group
              = f.label :"名 (全角)" , class: "ur-form-group__label"
              %span.ur-form-group__span 必須
              = f.text_field :first_name, autofocus: true, autocomplete: "first_name" ,placeholder:"例) 彩", class: "ur-form-group__field"
            .ur-form-group
              = f.label :"姓カナ (全角)" , class: "ur-form-group__label"
              %span.ur-form-group__span 必須
              = f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" ,placeholder:"例) ヤマダ", class: "ur-form-group__field"
            .ur-form-group
              = f.label :"名カナ (全角)" , class: "ur-form-group__label"
              %span.ur-form-group__span 必須
              = f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" ,placeholder:"例) アヤ", class: "ur-form-group__field"
            .ur-form-group
              = f.label :"生年月日" , class: "ur-form-group__label"
              %span.ur-form-group__span 必須
              .ur-form-group-birthday
                .ur-form-group-birthday__wrap
                  = date_select :birthday, '', {order: [ :year, :month, :day ],use_month_numbers: true,start_year: 1900,include_blank:true,end_year:Time.now.year,datetime_separator: '%s'}, {class: "  ur-form-group-birthday__wrap--select"}
            %p.ur-form-group__text.ur-form-group-info-text ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
            .ur-form-group
              %p.ur-form-group__text.ur-form-group__center 次へ進むのボタンを押すことにより、利用規約に同意したものとみなします

            .ur-form__btn
              = f.submit "次へ進む",class: "ur-form__btn--submit ur-form__btn--default ur-form__btn--red"
          / = render "devise/shared/links"

= render "devise/shared/login-footer"

app/views/users/profile.html.haml
= render 'users/top-header'
= render 'users/camera-btn'
.um-default
  - breadcrumb :profile
  = render 'users/bread-crumbs'
  .um-container
    .up-content
      %section
        %h2.up-content__head プロフィール
        = form_for "@users" do |f|   #モデル作成後に""外して実装します
          .up-setting-profile
            %figure.up-setting-profile__box
              = image_tag 'member_photo_noimage_thumb.png', class: "up-circle-image"
            = f.text_field :nickname, class: 'up-setting-profile__input', placeholder: '例)AYA☆セール中'
          .up-setting-introduction
            = f.text_area :introduction, class: 'up-setting-introduction__input', placeholder: '例）こんにちは☆ ご覧いただきありがとうございます！テラかわいいものやきれいめオフィスカジュアル中心に出品しています。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪'
            = f.submit '変更する', class: 'up-btn-default btn-red'
    = render 'devise/shared/side_bar'
= render 'users/top-footer'

app/views/users/userlogout.html.haml
= render 'users/top-header'
.um-default
  - breadcrumb :userlogout
  = render 'users/bread-crumbs'
  .uo-container.clearfix
    = render 'devise/shared/side_bar'
    .uo-right
      .uo-logout
        = button_to destroy_user_session_path,class: 'uo-btn',method: :delete do
          ログアウト
= render 'users/camera-btn'
= render 'users/top-footer'