config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
  }
  resources :categories, only: [:index, :show]
  resources :middle_categories, only: [:index, :show]
  resources :lower_categories, only: [:index, :show]
  resources :brands, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items do
    get :search, on: :collection
    resources :likes, only: [:create]
    resources :comments, only: [:create]
    resources :orders, only:[:new, :create]
  end
  root 'items#index'
  get 'users/new'
  post 'users/create'
  get 'top', to: 'items#top'
  get 'mypage', to: 'users#mypage'
  get 'profile', to: 'users#profile'
  get 'userconfirm', to: 'users#userconfirm'
  get 'userlogout', to: 'users#userlogout'
  get 'credit', to: 'users#credit'
  get 'creditregistration', to: 'users#creditregistration'
  get 'itemconfirm', to: 'users#itemconfirm'
  get 'sign_up', to: 'users#sign_up'
  get 'itemsell', to: 'users#itemsell'

  resources :credit_card, only:[:index, :new, :create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  belongs_to :user
  belongs_to :prefecture
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy

  def like?(user)
    like_users.include?(user)
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  enum status: {
                  very_good: 0,
                  good:      1,
                  normal:    2,
                  bad:       3,
                  so_bad:    4,
                  very_bad:  5
  }
  enum delivery_fee: {
                  include:  0,
                  exclude:  1
  }
  enum delivery_date: {
                        one_to_two:    0,
                        two_to_three:  1,
                        four_to_seven: 2
  }
  enum delivery_method: {
                          undecided:           0,
                          easy_mercari_mail:   1,
                          yu_yu_mercari_mail:  2,
                          large_mericari_mail: 3,
                          postal_mail:         4,
                          letter_pack:         5,
                          regular_mail:        6,
                          kuroneko_yamato:     7,
                          yu_pack:             8,
                          click_post:          9,
                          yu_packet:           10
}
  enum size: {
                underXXS: 0,
                XS: 1,
                S: 2,
                M: 3,
                L: 4,
                XL: 5,
                two_XL: 6,
                three_XL: 7,
                four_XL: 8,
                FREE_SIZE: 9
  }
  enum item_status: {
                  on_sale:  0,
                  sold_out:  1
  }

validates :name, presence: true
end

app/models/item_form.rb
class ItemForm
    include ActiveModel::Model
  validates :images,presence: {message: "画像がありません"}
  validates :name, presence: {message:"40字以内で入力してください"},length: { maximum: 40 ,message: "40字以内で入力してください"}
  validates :description, presence: {message:"1000字以内で入力してください"},length: { maximum: 1000 ,message: "1000字以上で入力してください"}
  validates :category_id, presence: {message:"入力してください"}
  validates :brand_id, presence: {message:"入力してください"}
  validates :status, presence: {message:"入力してください"}
  validates :delivery_fee, presence: {message:"入力してください"}
  validates :delivery_date, presence: {message:"入力してください"}
  validates :delivery_method, presence: {message:"入力してください"}
  validates :prefecture_id, presence: {message:"入力してください"}
  validates :price, presence: {message:"300以上9999999以下で入力してください"}
  validates :price,numericality: { only_integer: true,greater_than: 299,less_than:10000000 ,message:"300以上9999999以下で入力してください"}

  attr_accessor       :name,
                      :description,
                      :category_id,
                      :brand_id,
                      :status,
                      :delivery_fee,
                      :delivery_method,
                      :prefecture_id,
                      :delivery_date,
                      :price,
                      :images,
                      :remove_images,
                      :user_id,
                      :id

  def initialize(attr = {})
    if attr[:id] #商品のIDがある時(edit or update)
      if attr[:name] #updateの時
        attr.each do |k,v|
          self.send("#{k}=", v)
        end
      else #editの時
        @item = Item.find(attr[:id])
        item_params = @item.attributes
        item_params.each do |k,v|
          self.send("#{k}=", v) if self.methods.include?(k.to_sym)
        end
      end
    else
      super(attr)
    end
  end

  def save
    return false if invalid?
    item = Item.new(item_params)
    images.each do |i|
      item.images.new(image: i)
      item.save
    end
  end

  def update
    @item = Item.find(id)
    self.images = @item.images unless images
    return false if invalid?
    if remove_images
      remove_images.each do |r|
        @item.images.find(r).destroy
      end
    end
    unless images == @item.images
      images.each do |i|
        @item.images.new(image: i)
        @item.save
      end
    end
        @item.update(item_params)
  end

  private

  def item_params
    {
      name: name,
      description: description,
      category_id: category_id,
      brand_id: brand_id,
      status: status,
      delivery_fee: delivery_fee,
      delivery_method: delivery_method,
      prefecture_id: prefecture_id,
      delivery_date: delivery_date,
      price: price,
      user_id:user_id
    }
  end



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show,:search]

  def index
    @ladies = Item.where(category_id: 1).order("created_at DESC").limit(4)
    @mens = Item.where(category_id: 2).order("created_at DESC").limit(4)
    @kids = Item.where(category_id: 3).order("created_at DESC").limit(4)
    @cosmetics = Item.where(category_id: 7).order("created_at DESC").limit(4)
    @chanels = Item.where(brand_id: 1).order("created_at DESC").limit(4)
    @vuittons = Item.where(brand_id: 3).order("created_at DESC").limit(4)
    @supremes = Item.where(brand_id: 4).order("created_at DESC").limit(4)
    @nikes = Item.where(brand_id: 2).order("created_at DESC").limit(4)
  end

  def new
    @item_form = ItemForm.new
  end

  def create
    @item_form = ItemForm.new(item_params)
    if @item_form.save
        redirect_to root_path
      else
        @errors = @item_form.errors
        render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    other_items = Item.where.not(id: params[:id])

    near_items = other_items.where(category_id: @item.category.id)
    @prev_item = near_items[rand(near_items.length)]
    more_near_items = near_items.where.not(id: @prev_item.id)
    @next_item = more_near_items[rand(more_near_items.length)]

    @comment = Comment.new
    @comments = @item.comments

    @user_items = other_items.where(user_id: @item.user.id).limit(6)
    @category_items = other_items.where(category_id: @item.category.id).limit(6)
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to root_path
  end


  def edit
    @item_form = ItemForm.new(id:params[:id])
  end

  def update
    @item_form = ItemForm.new(item_params.merge(id:params[:id]))
    if @item_form.update
        redirect_to root_path
      else
        @errors = @item_form.errors
        render :edit
    end
  end


  def search
    result = []
    if params[:keyword].blank?
      redirect_to root_path
    else
      split_keyword = params[:keyword].split(/[[:blank:]]+/)
      split_keyword.each_with_index do |keyword, index|
        if index == 0
          result[index] = Item.where("name LIKE(?) OR description LIKE(?)", "%#{keyword}%","%#{keyword}%")
        else
          result[index] = result[index-1].where("name LIKE(?) OR description LIKE(?)", "%#{keyword}%","%#{keyword}%")
        end
      end
        if result[split_keyword.length-1] != []
          @items = result[split_keyword.length-1].order("id DESC").page(params[:page]).per(48)
        else
          @items = Item.limit(24).order("id DESC").page(params[:page]).per(48)
          @error = "該当する商品が見当たりません。商品は毎日増えていますので、これからの出品に期待してください。"
        end
    end
  end

  private

  def item_params
    params.require(:item_form).permit(
      :name,
      :description,
      :category_id,
      :brand_id,
      :status,
      :delivery_fee,
      :delivery_method,
      :prefecture_id,
      :delivery_date,
      :price,
       {:remove_images => []},
       { :images => [] }
      ).merge(user_id:current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  def converting_to_jpy(price)
    "¥ #{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/views/items/_image.html.haml
%li.is-image-li
  %figure.is-image-li__figure
    = image_tag image.image.url
  .is-image-li__under
    = link_to "#",class: "is-image-li__under--e" do
      編集
    = link_to "#",class: "is-image-li__under--e" ,id:"is-remove" ,data: {id:image.id} do
      削除

app/views/items/_item_form.html.haml
.is-content
  %main.is-main
    %section.is-section
      %h2.is-m-header 商品の情報を入力
      .is-form
        = form_with model: @item_form, url: items_path do |f|
          .is-upload-box
            .is-upload-box__head
              %h3.is-upload-box__head--text 出品画像
              %span.is-upload-box__head--red 必須
            %p.is-upload-box__head-p 最大10枚までアップロードできます
            .is-upload-box-container.clearfix
              .is-add-image
                .is-image-ul.item-0
                  %ul#is-image-ul-1
              .is-add-image
                .is-image-ul.item-0
                  %ul#is-image-ul-2
              = f.label :images ,class: "is-upload-box-container__box" ,id: "is-add",for: "is-img-0" do
                .is-add-up
                  = f.file_field :images,id: "is-img-0",multiple: true,data: {id: 0},class: "is-upload-box-container__box--file is-up-img"
                  %pre.is-upload-box-container__box--text ドラッグアンドドロップまたはクリックしてファイルをアップロード
              %ul.is-error-message
                %li.is-error-message__li
                  = @errors[:images][0] if @errors && @errors[:images][0]
          .is-sell-content
            .is-form-group
              = f.label :name ,:商品名,class: "is-form-group__label"
              %span.is-form-group__span 必須
              = f.text_field :name, autofocus: true, placeholder: "商品名（必須 40文字まで)", class: "is-form-group__field"
              %ul.is-error-message
                %li.is-error-message__li
                  = @errors[:name][0] if @errors && @errors[:name][0]
            .is-form-group
              = f.label :description ,:商品の説明,class: "is-form-group__label"
              %span.is-form-group__span 必須
              = f.text_area :description,row: 5,placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "is-form-group__area"
              %ul.is-error-message
                %li.is-error-message__li
                  = @errors[:description][0]if @errors && @errors[:description][0]
          .is-sell-content.clearfix
            %h3.is-sell-sub-head 商品の詳細
            .is-sell-form-box
              .is-form-group
                = f.label :category_id ,:カテゴリー,class: "is-form-group__label"
                %span.is-form-group__span 必須
                .is-select-wrap
                  = f.select :category_id,Category.all.map{|k| [k.name, k.id]}, {include_blank: true}, {class: "is-form-group__select"}
                %ul.is-error-message
                  %li.is-error-message__li
                    = @errors[:category_id][0] if @errors && @errors[:category_id][0]
              .is-form-group
                = f.label :brand_id ,:ブランド,class: "is-form-group__label"
                %span.is-form-group__span 必須
                .is-select-wrap
                  = f.select :brand_id,Brand.all.map{|k| [k.name, k.id]}, {include_blank: true}, {class: "is-form-group__select"}
                %ul.is-error-message
                  %li.is-error-message__li
                    = @errors[:brand_id][0] if @errors && @errors[:brand_id][0]
              .is-form-group
                = f.label :status ,:商品の状態,class: "is-form-group__label"
                %span.is-form-group__span 必須
                .is-select-wrap
                  = f.select :status,Item.statuses.keys.map {|k| [t("enums.item.status.#{k}"), k]},{include_blank: true}, {class: "is-form-group__select"}
                %ul.is-error-message
                  %li.is-error-message__li
                    = @errors[:status][0] if @errors && @errors[:status][0]
          .is-sell-content.clearfix
            %h3.is-sell-sub-head 配送について
            .is-sell-form-box
              .is-form-group
                = f.label :delivery_fee ,:配送料の負担 ,class: "is-form-group__label"
                %span.is-form-group__span 必須
                .is-select-wrap
                  = f.select :delivery_fee,Item.delivery_fees.keys.map{|k| [t("enums.item.delivery_fee.#{k}"), k]},{include_blank: true}, {class: "is-form-group__select"}
                %ul.is-error-message
                  %li.is-error-message__li
                    = @errors[:delivery_fee][0] if @errors && @errors[:delivery_fee][0]
              .is-form-group
                = f.label :delivery_method ,:配送料の方法 ,class: "is-form-group__label-hiden",id: "is-delivery_method"
                %span#is-delivery_method-span.is-form-group__span.is-form-group__hiden 必須
                .is-select-wrap#is-select-wrap-dm
                  = f.select :delivery_method,Item.delivery_methods.keys.map{|k| [t("enums.item.delivery_method.#{k}"), k]}, {include_blank: true}, {class: "is-form-group__select is-form-group__hiden",id: "item_form_delivery_method-include"}
                  = f.select :delivery_method,Item.delivery_methods.slice(:undecided,:postal_mail,:kuroneko_yamato,:yu_pack).keys.map{|k| [t("enums.item.delivery_method.#{k}"), k]}, {include_blank: true}, {class: "is-form-group__select is-form-group__hiden",id: "item_form_delivery_method-exclude"}
                %ul.is-error-message
                  %li#is-dm-error.is-error-message__li.is-form-group__hiden
                    = @errors[:delivery_method][0] if @errors && @errors[:delivery_method][0]
              .is-form-group
                = f.label :prefecture_id,:発送元の地域,class: "is-form-group__label"
                %span.is-form-group__span 必須
                .is-select-wrap
                  = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{prompt: ""},{class: "is-form-group__select"}
                %ul.is-error-message
                  %li.is-error-message__li
                    = @errors[:prefecture_id][0] if @errors && @errors[:prefecture_id][0]
              .is-form-group
                = f.label :delivery_date,:発送までの日数,class: "is-form-group__label"
                %span.is-form-group__span 必須
                .is-select-wrap
                  = f.select :delivery_date,Item.delivery_dates.keys.map {|k| [t("enums.item.delivery_date.#{k}"), k]}, {include_blank: true}, {class: "is-form-group__select"}
                %ul.is-error-message
                  %li.is-error-message__li
                    = @errors[:delivery_date][0] if  @errors && @errors[:delivery_date][0]
          .is-sell-content.clearfix
            %h3.is-sell-sub-head 販売価格(300〜9,999,999)
            .is-sell-form-box
              %ul.is-sell-price
                %li.is-form-group.is-sell-price__li
                  .clearfix
                    = f.label :price ,:価格,class: "is-form-group__label is-left"
                    %span.is-form-group__span 必須
                    .is-sell-price__input.is-right
                      = f.text_field :price, autofocus: true, placeholder: "例）300", class: "is-form-group__field is-sell-price__input--text"
                  %ul.is-error-message
                    %li.is-error-message__li
                      = @errors[:price][0] if @errors && @errors[:price][0]
                %li.clearfix.is-sell-price__li
                  .is-left
                    販売手数料(10%)
                  .is-right.is-sell-price__li--small#is-commission
                    -
                %li.clearfix.bold.is-sell-price__li
                  .is-left.is-bold
                    販売利益
                  .is-right.is-sell-price__li--large#is-profit
                    -
          .is-sell-content
            %p.is-sell-content__p 禁止されている出品、行為を必ずご確認ください。
            %p.is-sell-content__p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            %p.is-sell-content__p また、出品をもちまして加盟店規約に同意したことになります。
            = f.submit "出品する",class: "is-btn-default is-btn-red is-sell-content__btn"
            = link_to "もどる", root_path,class: "is-btn-default is-btn-gray is-sell-content__btn-under"

app/views/items/_search_items.html.haml
= link_to item_path (item) do
  = image_tag(item.images[0].image.url, class: "search-result__image") if item.images[0]
  %h4.search-result__introduction
    = item.name
  %h4.search-result__price
    ¥
    = item.price
  %p (税込)

app/views/items/index.html.haml
= render 'users/top-header'
= render 'users/camera-btn'
.top-contents
  %section
    .top-banner
      .top-banner__slides
        %div
          .top-banner__slides--inner-left
            %h2
              スマホでかんたん
              %br
              フリマアプリ
            %p
              メルカリはスマホカメラからすぐに出品できる
              %br
              購入時も安心な独自システムのアプリです
            .top-logo
              = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?4136293187"
              = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?4136293187"
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?4136293187",class: "iphone-picture"
      .top-banner__slides--newlife
        = link_to "",root_path,class: "top-banner banner-newlife"
      .top-banner__slides--advertisement
        = link_to "",root_path,class: "top-banner banner-advertisement"

  %section.top-pickup-contents
    %h2.pickup-head ピックアップカテゴリー
    %section.items-box-container.clearfix
      = render 'items/items_top/ladies',collection: @ladies
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/mens',collection: @mens
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/kids',collection: @kids
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/cosmetics', item: @cosmetics
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"

    %h2.pickup-head ピックアップブランド
    %section.items-box-container.clearfix
      = render 'items/items_top/chanels', collection: @chanels
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/vuittons', collection: @vuittons
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/supremes',collection: @supremes
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/nikes',collection: @nikes
      .view-all
        = link_to "すべての商品を見る", "/", class:"all-items"
= render 'users/top-footer'

app/views/items/new.html.haml
= render "devise/shared/login-header"
= render "items/item_form"
= render "devise/shared/login-footer"

app/views/items/search.html.haml
.search-default
  = render 'users/top-header'
  - breadcrumb :search
  = render 'users/bread-crumbs'
  .search-container
    .search-container__left
    .search-container__right
      %section.item-box-container
        %h2.search-result-head
          - if @error
            %h2
              = "検索結果 0件"
            %p
              = @error
            %h3 新着商品
            .search-result
              .search-result__items
                = render partial: 'items/search_items', collection: @items, as: "item"
          - else
            %h2
              = "検索結果 1-#{@items.length}件"
            .search-result
              .search-result__items
                = render partial: 'items/search_items', collection: @items, as: "item"
      .search-container__pager
        = paginate(@items)

  = render 'users/camera-btn'
  = render 'users/top-footer'

app/views/items/show.html.haml
.is-wrapper
  = render 'users/top-header'
  = render 'users/bread-crumbs'

  %aside.is-modal
    .is-modal__inner
      .is-modal__body
        %p 確認
        = "削除すると二度と復活できません。"
        %br
        = "削除する代わりに停止することもできます。"
        %br
        %br
        = "本当に削除しますか？"
      .clearfix
        .cancel-btn キャンセル
        = button_to '削除する', item_path(@item), method: :delete, class: 'delete-change cancel-btn', onfocus:"this.blur();"


  %section{ class: "#{@item.images.length < 5 ? 'is-item' : 'is-item is-many-photos' }"}
    %h1.is-item__name #{@item.name}
    .is-item__main.clearfix
      .is-item__photos
        - if @item.item_status == "sold_out"
          .is-soldout-badge
            .is-sold SOLD
        .is-slider
          - @item.images.each do |img|
            .is-slider__item
              = image_tag(img.image.url)
        .is-thumbnails
          - @item.images.each do |img|
            .is-thumbnails__item
              = image_tag(img.image.url)

      %table.is-item__detail
        %tr
          %th 出品者
          %td
            = link_to "#" do
              #{@item.user.nickname}
            .is-item__detail__icons
              .is-item__detail__icons--one
                = fa_icon 'smile-o'
                %span 0
              .is-item__detail__icons--one
                = fa_icon 'meh-o'
                %span 0
              .is-item__detail__icons--one
                = fa_icon 'frown-o'
                %span 999
        %tr
          %th カテゴリー
          %td
            %ul
              %li
                = link_to '#' do
                  #{@item.category.name}
              %li
                = link_to '#' do
                  = fa_icon 'angle-right'
                  %span #{@item.brand.name}
              %li
                = link_to '#' do
                  = fa_icon 'angle-right'
                  %span #{@item.name}
        %tr
          %th ブランド
          %td
            = link_to '' do
              #{@item.brand.name}
        %tr
          %th 商品の状態
          %td #{@item.status_i18n}
        %tr
          %th 配送料の負担
          %td #{@item.delivery_fee_i18n}
        %tr
          %th 配送の方法
          %td #{@item.delivery_method_i18n}
        %tr
          %th 配送元地域
          %td
            = link_to '' do
              #{@item.prefecture.name}
        %tr
          %th 発送日の目安
          %td #{@item.delivery_date_i18n}

    .is-item__price
      %span.is-item__price--bold
        = converting_to_jpy(@item.price)
      %span.is-item__price--tax (税込)
      %span.is-item__price--shipping-fee
        = "#{@item.delivery_fee_i18n}".gsub(/\(.+\)/,"")
    - if @item.user != current_user
      - if @item.item_status == "on_sale"
        = link_to "購入画面に進む", new_item_order_path(@item), class: "is-item__buy-btn"
      - else
        .is-gray.is-item__buy-btn 売り切れました

    .is-item__description
      %p.is-item__description--inner
        #{@item.description}

    - if @item.user != current_user
      .is-item__btns.clearfix
        .is-item__btns--left
          = render 'likes/like'
          = link_to "#", class: "is-item__btns--left--report btn" do
            = fa_icon "flag", class: "is-item__btns--left--report__icon"
            %span.is-item__btns--left--report__text 不適切な商品の報告
        .is-item__btns--right
          = link_to "https://www.mercari.com/jp/safe/description/", class: "is-item__btns--right--safe" do
            = fa_icon "lock", class: "is-item__btns--right--safe__icon"
            %span.is-item__btns--right--safe__text あんしん・あんぜんへの取り組み

  - if @item.user == current_user
    .is-item__change-box
      = link_to '商品の編集', '#', class: 'btn red'
      %p or
      .is-change.btn この商品を削除する

  .is-item__comment-block
    .is-item__comment__wrapper
      -if @comments.present?
        .is-item__comments
          %ul.comments
            = render partial: 'items/items_top/comment', collection: @comments
      .is-item__comments
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        = form_for [@item, @comment], html:{id: 'comment-form'} do |f|
          = f.text_area :comment, class: 'is-item__comment-form__textarea', placeholder: 'コメントを書いてください'
          - if @item.item_status == "on_sale"
            = f.submit 'コメントする', class: 'is-item__comment-form__btn'
          - else
            .is-item__comment-form__btn.is-gray 売り切れのためコメントできません

      - if @item.user != current_user
        %ul.is-item__navi.clearfix
          %li.is-item__navi--prev
            = link_to item_path(@prev_item), data: {"turbolinks"=>false}do
              = fa_icon "angle-left"
              = @prev_item.name
          %li.is-item__navi--next
            = link_to item_path(@next_item), data: {"turbolinks"=>false} do
              = @next_item.name
              = fa_icon "angle-right"

        .is-item__social-media-box
          .is-item__social-medias-text
          %ul.is-item__social-medias
            %li
              = link_to '' do
                = fa_icon 'facebook-square'
            %li
              = link_to '' do
                = fa_icon 'twitter-square'
            %li
              = link_to '' do
                = fa_icon 'pinterest-square'

        .is-item__relation
          - if @user_items.length != 0
            %section.is-item__relation__box
              %h2.is-item__ralation__box__title
                = link_to "#{@item.user.nickname}さんのその他の出品", "#", class: "items-box-container__title__topic"
              .is-item__relation__box__contents.clearfix
                = render partial: 'items/items_top/item', collection: @user_items, as: "item"
          - if @category_items.length != 0
            %section.is-item__relation__box
              %h2.is-item__ralation__box__title
                = link_to "#{@item.category.name} その他の出品", "#", class: "items-box-container__title__topic"
              .is-item__relation__box__contents.clearfix
                = render partial: 'items/items_top/item', collection: @category_items, as: "item"

  = render 'users/top-footer'

app/views/items/top.html.haml
= render 'users/top-header'
= render 'users/camera-btn'
.top-contents
  %section
    .top-banner
      .top-banner__slides
        %div
          .top-banner__slides--inner-left
            %h2
              スマホでかんたん
              %br
              フリマアプリ
            %p
              メルカリはスマホカメラからすぐに出品できる
              %br
              購入時も安心な独自システムのアプリです
            .top-logo
              = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?4136293187"
              = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?4136293187"
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?4136293187",class: "iphone-picture"
      .top-banner__slides--newlife
        = link_to "",root_path,class: "top-banner banner-newlife"
      .top-banner__slides--advertisement
        = link_to "",root_path,class: "top-banner banner-advertisement"

  %section.top-pickup-contents
    %h2.pickup-head ピックアップカテゴリー
    %section.items-box-container.clearfix
      = render 'items/items_top/ladies',collection: @ladies
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/mens',collection: @mens
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/kids',collection: @kids
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/cosmetics', item: @cosmetics
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"

    %h2.pickup-head ピックアップブランド
    %section.items-box-container.clearfix
      = render 'items/items_top/chanels', collection: @chanels
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/vuittons', collection: @vuittons
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/supremes',collection: @supremes
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"

    %section.items-box-container.clearfix
      = render 'items/items_top/nikes',collection: @nikes
      .view-all
        = link_to "すべての商品を見る", "/test/", class:"all-items"
= render 'users/top-footer'